// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp-o_SUlfOtntnLGr6-LP0Yuk3YJTJ8Es',
    appId: '1:546635644438:web:54975b0dd428464bed7f37',
    messagingSenderId: '546635644438',
    projectId: 'fir-flutter-codelab-4fbb1',
    authDomain: 'fir-flutter-codelab-4fbb1.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-4fbb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfTNeS-VouRNaT5lvjoUqXIJoSdw409uU',
    appId: '1:546635644438:android:3574812de60e1320ed7f37',
    messagingSenderId: '546635644438',
    projectId: 'fir-flutter-codelab-4fbb1',
    storageBucket: 'fir-flutter-codelab-4fbb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQqH7C41qYH5K8-iQFaOCh6fOQMkgQyeM',
    appId: '1:546635644438:ios:6648b14edaf572d9ed7f37',
    messagingSenderId: '546635644438',
    projectId: 'fir-flutter-codelab-4fbb1',
    storageBucket: 'fir-flutter-codelab-4fbb1.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQqH7C41qYH5K8-iQFaOCh6fOQMkgQyeM',
    appId: '1:546635644438:ios:6648b14edaf572d9ed7f37',
    messagingSenderId: '546635644438',
    projectId: 'fir-flutter-codelab-4fbb1',
    storageBucket: 'fir-flutter-codelab-4fbb1.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp-o_SUlfOtntnLGr6-LP0Yuk3YJTJ8Es',
    appId: '1:546635644438:web:6c138c7ff5d76a11ed7f37',
    messagingSenderId: '546635644438',
    projectId: 'fir-flutter-codelab-4fbb1',
    authDomain: 'fir-flutter-codelab-4fbb1.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-4fbb1.appspot.com',
  );
}
